import Head from "next/head";
import Image from "next/image";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import emailjs from "@emailjs/browser";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { useState, useRef } from "react";
import Link from "next/link";
import PortfolioCard from "../components/PortfolioCard";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  const ref = useRef<null | HTMLDivElement>(null);
  const formRef = useRef<null | HTMLFormElement>(null);

  const scrollToContact = () => {
    if (ref.current && ref.current.scrollIntoView) {
      ref.current.scrollIntoView({ behavior: "smooth" });
    }
  };

  const sendEmail = (e: any) => {
    e.preventDefault();

    if (formRef.current) {
      emailjs
        .sendForm(
          "service_8kopajf",
          "template_9vgtetv",
          formRef.current,
          "_-7KLnb9aw5BKkyw0"
        )
        .then(
          (result) => {
            toast("Message sent successfully");
          },
          (error) => {
            toast(`Could not send email: ${error.text}`);
          }
        );
    }
  };

  const works = [
    {
      src: "/web1.png",
      alt: "Deliverize Restaurant",
      title: "Deliverize Restaurant",
      key: 1,
    },
    {
      src: "/web1.png",
      alt: "Portfolio project 2",
      title: "Deliverize Homepage",
      key: 2,
    },
    {
      src: "/web1.png",
      alt: "Portfolio project 3",
      title: "Deliverize Homepage",
      key: 3,
    },
    {
      src: "/web1.png",
      alt: "Portfolio project 4",
      title: "Deliverize Homepage",
      key: 4,
    },
    {
      src: "/web1.png",
      alt: "Portfolio project 5",
      title: "Deliverize Homepage",
      key: 5,
    },
    {
      src: "/web1.png",
      alt: "Portfolio project 6",
      title: "Deliverize Homepage",
      key: 6,
    },
  ];

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Thiago Nascimbeni - Software Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-6 md:px-20 lg:px-40 transition dark:bg-gray-900">
        <section>
          <nav className="py-10 mb-12 flex justify-between">
            <h1
              onClick={scrollToContact}
              className="text-xl font-burtons cursor-pointer hover:text-teal-600 transition dark:text-white dark:hover:text-teal-600"
            >
              CONTACT
            </h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl hover:text-teal-600 transition dark:text-white dark:hover:text-teal-600"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>

          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl border-b-2 border-teal-600">
              Thiago <br /> Nascimbeni
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white">
              Software Developer & Designer.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-gray-300">
              Freelancer providing services for programming content needs. Join
              me down below and let&apos;s get started!
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-white">
            <Link href={"https://github.com/Thiagomn1/"} passHref>
              <AiFillGithub className="hover:cursor-pointer hover:text-teal-600 transition " />
            </Link>
            <Link
              href={"https://www.linkedin.com/in/thiago-nascimbeni-3b6a1b179/"}
              passHref
            >
              <AiFillLinkedin className="hover:cursor-pointer hover:text-teal-600 transition" />
            </Link>
            <Link href={"https://twitter.com/thiagomn12"} passHref>
              <AiFillTwitterCircle className="hover:cursor-pointer hover:text-teal-600 transition" />
            </Link>
          </div>

          <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden my-8">
            <Image
              className="object-cover"
              src={"/header.svg"}
              fill
              alt="Header"
            />
          </div>
        </section>

        <section>
          <div className="md: text-center">
            <h3 className="text-3xl py-2 font-semibold dark:text-white">
              Services
            </h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-300">
              I offer services ranging from design, creating the look and feel
              of your website with tools like Figma and Photoshop, to developing
              it.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-300">
              I specialize in front-end, but with knowledge of back-end as well,
              making use primarily of React.js in the front-end and
              Node.js/Express for back-end content needs.
            </p>
          </div>

          <div className="lg:flex lg:justify-center gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 w-full dark:shadow-gray-800">
              <div className="flex justify-center">
                <Image
                  src={"/design.png"}
                  alt="Design"
                  width={100}
                  height={100}
                />
              </div>

              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-white">
                Design
              </h3>
              <p className="py-2 dark:text-gray-300">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10 w-full dark:shadow-gray-800 ">
              <div className="flex justify-center">
                <Image src={"/code.png"} alt="Code" width={100} height={100} />
              </div>

              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-white">
                Software Development
              </h3>
              <p className="py-2 dark:text-gray-300">
                Development with the use of popular frameworks such as
                React/Next.js, creating a clean and maintanable code for your
                website.
              </p>
            </div>
          </div>
        </section>

        <section>
          <div className="md: text-center">
            <h3 className="text-3xl py-1 font-semibold dark:text-white">
              Portfolio
            </h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-300">
              Always keeping myself updated with newly released technologies and
              studying on a daily basis to deliver quality projects.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-300">
              Check out some of my recent work below:
            </p>
          </div>

          <div className="flex justify-center flex-col gap-10 py-10 md:flex-row md:flex-wrap">
            {works.map((work) => (
              <PortfolioCard
                key={work.key}
                title={work.title}
                src={work.src}
                alt={work.alt}
              />
            ))}
          </div>
        </section>

        <section ref={ref}>
          <div className="md: text-center">
            <h3 className="text-3xl py-1 font-semibold dark:text-white">
              Contact me
            </h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-300">
              Let&apos;s hear about your
              <span className="text-teal-500"> project</span> ideas, contact me
              down below and let&apos;s get started!
            </p>
          </div>

          <div className="py-8 lg:py-16 px-4 mx-auto max-w-screen-md">
            <form ref={formRef} onSubmit={sendEmail} className="space-y-8">
              <div>
                <label
                  htmlFor="name"
                  className="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300"
                >
                  Your name
                </label>
                <input
                  type="text"
                  id="name"
                  className="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500 dark:shadow-sm-light"
                  placeholder="John Doe"
                  name="user_name"
                  required
                />
              </div>
              <div>
                <label
                  htmlFor="email"
                  className="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300"
                >
                  Your email
                </label>
                <input
                  type="email"
                  id="email"
                  className="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500 dark:shadow-sm-light"
                  placeholder="example@gmail.com"
                  name="user_email"
                  required
                />
              </div>
              <div className="sm:col-span-2">
                <label
                  htmlFor="message"
                  className="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-400"
                >
                  Your message
                </label>
                <textarea
                  id="message"
                  rows={6}
                  className="block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg shadow-sm border border-gray-300 focus:ring-primary-500 focus:border-primary-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500"
                  placeholder="Leave a message and let me know how i can help you..."
                  name="message"
                ></textarea>
              </div>
              <button
                type="submit"
                className="py-3 px-5 text-sm font-medium text-center rounded-lg bg-gradient-to-r from-cyan-500 to-teal-500 text-white sm:w-fit hover:bg-primary-800 focus:ring-4 focus:outline-none focus:ring-primary-300 dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800"
              >
                Send message
              </button>
            </form>
          </div>
        </section>
        <ToastContainer />
      </main>
    </div>
  );
}
